static const char *ClassId    = "$Id: DevServClass.cpp 13293 2009-04-07 10:53:56Z pascal_verdier $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source: $";
static const char *SvnPath    = "$HeadURL: $";
static const char *HttpServer = "http://www.esrf.fr/computing/cs/tango/tango_doc/ds_doc/";
//+=============================================================================
//
// file :        CornerStone130Class.cpp
//
// description : C++ source for the CornerStone130Class. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the CornerStone130 once per process.
//
// project :     TANGO Device Server
//
// $Author: pascal_verdier $
//
// $Revision: 13293 $
//
// $Log$
// Revision 3.11  2007/10/23 14:04:30  pascal_verdier
// Spelling mistakes correction
//
// Revision 3.10  2006/11/15 14:17:10  pascal_verdier
// Remove warnings from compiler.
//
// Revision 3.9  2006/06/26 09:31:03  pascal_verdier
// Tango-5.5 compatiblity.
// extern C method added to be used as shared library.
// VCC 6 project file generated if running on Win32.
// .obj, .so, executable files generated in separated directories.
//
// Revision 3.8  2005/09/08 08:45:23  pascal_verdier
// For Pogo-4.4.0 and above.
//
// Revision 3.7  2005/06/17 08:53:21  pascal_verdier
// CVS tags management added.
//
// Revision 3.6  2005/05/19 13:11:18  pascal_verdier
// *** empty log message ***
//
// Revision 3.5  2005/03/02 14:06:15  pascal_verdier
// namespace is different than class name.
//
// Revision 3.4  2004/12/10 13:23:27  pascal_verdier
// Pogo-4.0.0 (Ready for Tango5).
//
// Revision 3.3  2004/11/08 14:27:21  pascal_verdier
// *** empty log message ***
//
// Revision 3.2  2004/11/08 11:33:16  pascal_verdier
// if device property not found in database, it takes class property value if exists.
//
// Revision 3.1  2004/09/06 09:27:05  pascal_verdier
// Modified for Tango 5 compatibility.
//
//
// copyleft :   European Synchrotron Radiation Facility
//              BP 220, Grenoble 38043
//              FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <tango.h>

#include <CornerStone130.h>
#include <CornerStone130Class.h>


//+----------------------------------------------------------------------------
/**
 *	Create CornerStone130Class singleton and return it in a C function for Python usage
 */
//+----------------------------------------------------------------------------
extern "C" {
#ifdef WIN32

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_CornerStone130_class(const char *name) {
		return CornerStone130_ns::CornerStone130Class::init(name);
	}
}


namespace CornerStone130_ns
{
//+----------------------------------------------------------------------------
//
// method : 		AbortClass::execute()
// 
// description : 	method to trigger the execution of the command.
//                PLEASE DO NOT MODIFY this method core without pogo   
//
// in : - device : The device on which the command must be executed
//		- in_any : The command input data
//
// returns : The command output data (packed in the Any object)
//
//-----------------------------------------------------------------------------
CORBA::Any *AbortClass::execute(Tango::DeviceImpl *device,const CORBA::Any &in_any)
{

	cout2 << "AbortClass::execute(): arrived" << endl;

	((static_cast<CornerStone130 *>(device))->abort());
	return new CORBA::Any();
}



//
//----------------------------------------------------------------
//	Initialize pointer for singleton pattern
//----------------------------------------------------------------
//
CornerStone130Class *CornerStone130Class::_instance = NULL;

//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::CornerStone130Class(string &s)
// 
// description : 	constructor for the CornerStone130Class
//
// in : - s : The class name
//
//-----------------------------------------------------------------------------
CornerStone130Class::CornerStone130Class(string &s):DeviceClass(s)
{

	cout2 << "Entering CornerStone130Class constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();
	
	cout2 << "Leaving CornerStone130Class constructor" << endl;

}
//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::~CornerStone130Class()
// 
// description : 	destructor for the CornerStone130Class
//
//-----------------------------------------------------------------------------
CornerStone130Class::~CornerStone130Class()
{
	_instance = NULL;
}

//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::instance
// 
// description : 	Create the object if not already done. Otherwise, just
//			return a pointer to the object
//
// in : - name : The class name
//
//-----------------------------------------------------------------------------
CornerStone130Class *CornerStone130Class::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new CornerStone130Class(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

CornerStone130Class *CornerStone130Class::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}

//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::command_factory
// 
// description : 	Create the command object(s) and store them in the 
//			command list
//
//-----------------------------------------------------------------------------
void CornerStone130Class::command_factory()
{
	command_list.push_back(new AbortClass("Abort",
		Tango::DEV_VOID, Tango::DEV_VOID,
		"",
		"",
		Tango::OPERATOR));

	//	add polling if any
	for (unsigned int i=0 ; i<command_list.size(); i++)
	{
	}
}

//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::get_class_property
// 
// description : 	Get the class property for specified name.
//
// in :		string	name : The property name
//
//+----------------------------------------------------------------------------
Tango::DbDatum CornerStone130Class::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::get_default_device_property()
// 
// description : 	Return the default value for device property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum CornerStone130Class::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::get_default_class_property()
// 
// description : 	Return the default value for class property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum CornerStone130Class::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::device_factory
// 
// description : 	Create the device object(s) and store them in the 
//			device list
//
// in :		Tango::DevVarStringArray *devlist_ptr : The device name list
//
//-----------------------------------------------------------------------------
void CornerStone130Class::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	//	Create all devices.(Automatic code generation)
	//-------------------------------------------------------------
	for (unsigned long i=0 ; i < devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
						
		// Create devices and add it into the device list
		//----------------------------------------------------
		device_list.push_back(new CornerStone130(this, (*devlist_ptr)[i]));							 

		// Export device to the outside world
		// Check before if database used.
		//---------------------------------------------
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(device_list.back());
		else
			export_device(device_list.back(), (*devlist_ptr)[i]);
	}
	//	End of Automatic code generation
	//-------------------------------------------------------------

}
//+----------------------------------------------------------------------------
//	Method: CornerStone130Class::attribute_factory(vector<Tango::Attr *> &att_list)
//-----------------------------------------------------------------------------
void CornerStone130Class::attribute_factory(vector<Tango::Attr *> &att_list)
{
	//	Attribute : gratingNumber
	gratingNumberAttrib	*grating_number = new gratingNumberAttrib();
	Tango::UserDefaultAttrProp	grating_number_prop;
	grating_number_prop.set_label("gratingNumber");
	grating_number_prop.set_max_value("2");
	grating_number_prop.set_min_value("1");
	grating_number_prop.set_description("Current grating number");
	grating_number->set_default_properties(grating_number_prop);
	att_list.push_back(grating_number);

	//	Attribute : gratingLabel
	gratingLabelAttrib	*grating_label = new gratingLabelAttrib();
	Tango::UserDefaultAttrProp	grating_label_prop;
	grating_label_prop.set_label("gratingLabel");
	grating_label_prop.set_description("Current gratting label.");
	grating_label->set_default_properties(grating_label_prop);
	att_list.push_back(grating_label);

	//	Attribute : gratingMinWL
	gratingMinWLAttrib	*grating_min_wl = new gratingMinWLAttrib();
	Tango::UserDefaultAttrProp	grating_min_wl_prop;
	grating_min_wl_prop.set_label("gratingMinWL");
	grating_min_wl_prop.set_description("Minimum wave length for current grating, in operational unit.");
	grating_min_wl->set_default_properties(grating_min_wl_prop);
	att_list.push_back(grating_min_wl);

	//	Attribute : gratingMaxWL
	gratingMaxWLAttrib	*grating_max_wl = new gratingMaxWLAttrib();
	Tango::UserDefaultAttrProp	grating_max_wl_prop;
	grating_max_wl_prop.set_label("gratingMaxWL");
	grating_max_wl_prop.set_description("Maximum wave length for current grating, in operational unit.");
	grating_max_wl->set_default_properties(grating_max_wl_prop);
	att_list.push_back(grating_max_wl);

	//	Attribute : filterNumber
	filterNumberAttrib	*filter_number = new filterNumberAttrib();
	Tango::UserDefaultAttrProp	filter_number_prop;
	filter_number_prop.set_label("filterNumber");
	filter_number_prop.set_max_value("6");
	filter_number_prop.set_min_value("1");
	filter_number_prop.set_description("Current filter number.");
	filter_number->set_default_properties(filter_number_prop);
	att_list.push_back(filter_number);

	//	Attribute : filterLabel
	filterLabelAttrib	*filter_label = new filterLabelAttrib();
	Tango::UserDefaultAttrProp	filter_label_prop;
	filter_label_prop.set_label("filterLabel");
	filter_label_prop.set_description("Current filter label");
	filter_label->set_default_properties(filter_label_prop);
	att_list.push_back(filter_label);

	//	Attribute : wavelength
	wavelengthAttrib	*wavelength = new wavelengthAttrib();
	Tango::UserDefaultAttrProp	wavelength_prop;
	wavelength_prop.set_label("wavelength");
	wavelength_prop.set_min_value("0");
	wavelength_prop.set_description("Current wave length value, in operational unit.");
	wavelength->set_default_properties(wavelength_prop);
	att_list.push_back(wavelength);

	//	Attribute : shutterClosed
	shutterClosedAttrib	*shutter_closed = new shutterClosedAttrib();
	Tango::UserDefaultAttrProp	shutter_closed_prop;
	shutter_closed_prop.set_label("shutterClosed");
	shutter_closed_prop.set_description("Current shutter state.");
	shutter_closed->set_default_properties(shutter_closed_prop);
	att_list.push_back(shutter_closed);

	//	End of Automatic code generation
	//-------------------------------------------------------------
}

//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::get_class_property()
// 
// description : 	Read the class properties from database.
//
//-----------------------------------------------------------------------------
void CornerStone130Class::get_class_property()
{
	//	Initialize your default values here (if not done with  POGO).
	//------------------------------------------------------------------

	//	Read class properties from database.(Automatic code generation)
	//------------------------------------------------------------------

	//	Call database and extract values
	//--------------------------------------------
	if (Tango::Util::instance()->_UseDb==true)
		get_db_class()->get_property(cl_prop);
	Tango::DbDatum	def_prop;
	int	i = -1;


	//	End of Automatic code generation
	//------------------------------------------------------------------

}

//+----------------------------------------------------------------------------
//
// method : 	CornerStone130Class::set_default_property
// 
// description: Set default property (class and device) for wizard.
//              For each property, add to wizard property name and description
//              If default value has been set, add it to wizard property and
//              store it in a DbDatum.
//
//-----------------------------------------------------------------------------
void CornerStone130Class::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;

	vector<string>	vect_data;
	//	Set Default Class Properties
	//	Set Default Device Properties
	prop_name = "Gratings";
	prop_desc = "List of {grating id : grating label : min wavelength : max wavelength}";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Filters";
	prop_desc = "List of {filter id : filter label}";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "OperationalUnit";
	prop_desc = "Operational unit, among: nm, um, wm.";
	prop_def  = "nm";
	vect_data.clear();
	vect_data.push_back("nm");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "GpibDeviceUrl";
	prop_desc = "GPIB device name.";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "PollingPeriod";
	prop_desc = "Polling period, in ms.";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "ReadDelay";
	prop_desc = "Read command delay, in ms. For expert only.";
	prop_def  = "100";
	vect_data.clear();
	vect_data.push_back("100");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "FilterWriteDelay";
	prop_desc = "Filter write delay, in ms.";
	prop_def  = "10000.0";
	vect_data.clear();
	vect_data.push_back("10000.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "GratingWriteDelay";
	prop_desc = "Grating write delay, in ms.";
	prop_def  = "10000.0";
	vect_data.clear();
	vect_data.push_back("10000.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "WaveLengthWriteDelay";
	prop_desc = "Wavelength write delay, in ms.";
	prop_def  = "10000.0";
	vect_data.clear();
	vect_data.push_back("10000.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

}
//+----------------------------------------------------------------------------
//
// method : 		CornerStone130Class::write_class_property
// 
// description : 	Set class description as property in database
//
//-----------------------------------------------------------------------------
void CornerStone130Class::write_class_property()
{
	//	First time, check if database used
	//--------------------------------------------
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Corner stone 130");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("This class is to interface the  CornerStone130 equipment on TANGO");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename(classname);
	filename += "Class.cpp";
	
	// Create a string with the class ID to
	// get the string into the binary
	string	class_id(ClassId);
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_4Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	//--------------------------------------------
	get_db_class()->put_property(data);
}

}	// namespace
